export const ALLOWED_INITIAL_STATUSES = [
  'PENDING_EMAIL_VERIFICATION',
  'PENDING_ADMIN_ASSIGNMENT',
  'PENDING_ADMIN_APPROVAL',
]
export const TARGET_STATUS = 'PENDING_ADMIN_APPROVAL'
export const DEFAULT_APP_URL = 'http://localhost:5173'